name: Generate save files

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Clone TTS tools
        run: git clone https://github.com/gavrilikhin-d/tts-tools

      - name: Install TTS tools deps
        working-directory: tts-tools
        run: pnpm install --frozen-lockfile

      - name: Build TTS tools
        working-directory: tts-tools
        run: pnpm -r --if-present build

      - name: Package Core
        working-directory: mods/core/scripts/objects
        run: node "${{ github.workspace }}/tts-tools/packages/cli/dist/index.js" package . -i . -o Core.json
