name: Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      luaVersion: '5.2'
    name: Lint
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --glob "**/*.ttslua" .

      - name: Commit and push formatting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "lint"
          file_pattern: "**/*.ttslua"

